### ISSUE TITLE
default value for sharpness

### ISSUE THREAD

**Issue by azumukupoe** [tappi287/openvr_fsr_app#17]
[openvr_fsr's default value for sharpness is 0.9](https://github.com/fholger/openvr_fsr#configuration) but this app sets it to 0.75 by default
is 0.75 the value recommended by you?

**Comment by tappi287** [comment]
I'd recommend the lowest possible sharpening value because aliasing is not addressed at all with FSR and contrast sharpening will make it worse. The default value comes from the original repo:
https://github.com/fholger/openvr_fsr/blob/f0f3667980b53ed86da7b8e7499a29881900d706/src/openvr_mod.cfg
I'll change it to 0.9 with the next release to be inline with the latest fsr release
