### ISSUE TITLE
Feature request: do not overwrite the config file, instead modify it

### ISSUE THREAD

**Issue by jacklul** [tappi287/openvr_fsr_app#24]
Currently your app completely overwrites the config file, so in case someone is using variables that can't be configured within the app they get removed.

It would be nice if config modification within the app kept any extra variables in that config file intact, this will make usage with custom forks with extra features easier.
Additionally the config file present in source directory for the dll should be used as a base so that extra variables are pre-set.

**Comment by tappi287** [comment]
> It would be nice if config modification within the app kept any extra variables in that config file intact, this will make usage with custom forks with extra features easier.

I'd like to support that but need to refactor the read/write methods constantly atm. I'll re-visit if the methods are flexible enough.

> Additionally the config file present in source directory for the dll should be used as a base so that extra variables are pre-set.

This won't be possible. The app will store every cfg setting it is aware of(instead of reading it from the cfg) per app/mod internally so the user doesn't loose these settings if he decides to uninstall a mod or change to a different mod.

**Comment by tappi287** [comment]
github.com/tappi287/openvr_fsr_app/releases/latest
Config for the VrPerfkit settings is now taken from the mod data dir and edited non-destructive. I can't support this for the older OpenVRMod "cfg"/json like formats.
