### ISSUE TITLE
Jet Island not working since version 0.3.0

### ISSUE THREAD

**Issue by fire4cavemen** [tappi287/openvr_fsr_app#32]
When I start the game on 0.8.4 or any of the previous versions since 0.3.0 I get a static image of the game on the monitor and the game stuck on launching in SteamVR.

To be clear, version 0.3.0 is working fine.

**Comment by tappi287** [comment]
Hey, 
that version of the app installed the mod only to the first encountered openvr dll. That means it most likley works because it is not installed at all.
0.3.0 of the app was using this mod version if you want to try it manually
https://github.com/fholger/openvr_fsr/releases/tag/fsr_v1.1

You could have a look at this https://github.com/fholger/openvr_fsr#troubleshooting and report the issue over there or at the successor project https://github.com/fholger/vrperfkit

There is nothing this app could do about that.
